name: Automatically Build Images

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  buildimage:
    runs-on: ubuntu-latest
    steps:
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/phantomic12/generic-arch:latest
          file: Dockerfile
